// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Practice.proto

#include "Practice.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

PROTOBUF_CONSTEXPR Practice::Practice(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.out_laps_)*/{}
  , /*decltype(_impl_.installation_laps_)*/{}
  , /*decltype(_impl_.aero_mapping_)*/{}
  , /*decltype(_impl_.performance_runs_)*/{}
  , /*decltype(_impl_.long_runs_)*/{}
  , /*decltype(_impl_.race_simulation_)*/{}
  , /*decltype(_impl_.qualifying_simulation_)*/{}
  , /*decltype(_impl_.practice_starts_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct PracticeDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PracticeDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~PracticeDefaultTypeInternal() {}
  union {
    Practice _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PracticeDefaultTypeInternal _Practice_default_instance_;
static ::_pb::Metadata file_level_metadata_Practice_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_Practice_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_Practice_2eproto = nullptr;

const uint32_t TableStruct_Practice_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Practice, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::Practice, _impl_.out_laps_),
  PROTOBUF_FIELD_OFFSET(::Practice, _impl_.installation_laps_),
  PROTOBUF_FIELD_OFFSET(::Practice, _impl_.aero_mapping_),
  PROTOBUF_FIELD_OFFSET(::Practice, _impl_.performance_runs_),
  PROTOBUF_FIELD_OFFSET(::Practice, _impl_.long_runs_),
  PROTOBUF_FIELD_OFFSET(::Practice, _impl_.race_simulation_),
  PROTOBUF_FIELD_OFFSET(::Practice, _impl_.qualifying_simulation_),
  PROTOBUF_FIELD_OFFSET(::Practice, _impl_.practice_starts_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::Practice)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::_Practice_default_instance_._instance,
};

const char descriptor_table_protodef_Practice_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\016Practice.proto\032\013Stint.proto\"\213\002\n\010Practi"
  "ce\022\030\n\010out_laps\030\001 \003(\0132\006.Stint\022!\n\021installa"
  "tion_laps\030\002 \003(\0132\006.Stint\022\034\n\014aero_mapping\030"
  "\003 \003(\0132\006.Stint\022 \n\020performance_runs\030\004 \003(\0132"
  "\006.Stint\022\031\n\tlong_runs\030\005 \003(\0132\006.Stint\022\037\n\017ra"
  "ce_simulation\030\006 \003(\0132\006.Stint\022%\n\025qualifyin"
  "g_simulation\030\007 \003(\0132\006.Stint\022\037\n\017practice_s"
  "tarts\030\010 \003(\0132\006.Stintb\006proto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_Practice_2eproto_deps[1] = {
  &::descriptor_table_Stint_2eproto,
};
static ::_pbi::once_flag descriptor_table_Practice_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_Practice_2eproto = {
    false, false, 307, descriptor_table_protodef_Practice_2eproto,
    "Practice.proto",
    &descriptor_table_Practice_2eproto_once, descriptor_table_Practice_2eproto_deps, 1, 1,
    schemas, file_default_instances, TableStruct_Practice_2eproto::offsets,
    file_level_metadata_Practice_2eproto, file_level_enum_descriptors_Practice_2eproto,
    file_level_service_descriptors_Practice_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_Practice_2eproto_getter() {
  return &descriptor_table_Practice_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_Practice_2eproto(&descriptor_table_Practice_2eproto);

// ===================================================================

class Practice::_Internal {
 public:
};

void Practice::clear_out_laps() {
  _impl_.out_laps_.Clear();
}
void Practice::clear_installation_laps() {
  _impl_.installation_laps_.Clear();
}
void Practice::clear_aero_mapping() {
  _impl_.aero_mapping_.Clear();
}
void Practice::clear_performance_runs() {
  _impl_.performance_runs_.Clear();
}
void Practice::clear_long_runs() {
  _impl_.long_runs_.Clear();
}
void Practice::clear_race_simulation() {
  _impl_.race_simulation_.Clear();
}
void Practice::clear_qualifying_simulation() {
  _impl_.qualifying_simulation_.Clear();
}
void Practice::clear_practice_starts() {
  _impl_.practice_starts_.Clear();
}
Practice::Practice(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:Practice)
}
Practice::Practice(const Practice& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  Practice* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.out_laps_){from._impl_.out_laps_}
    , decltype(_impl_.installation_laps_){from._impl_.installation_laps_}
    , decltype(_impl_.aero_mapping_){from._impl_.aero_mapping_}
    , decltype(_impl_.performance_runs_){from._impl_.performance_runs_}
    , decltype(_impl_.long_runs_){from._impl_.long_runs_}
    , decltype(_impl_.race_simulation_){from._impl_.race_simulation_}
    , decltype(_impl_.qualifying_simulation_){from._impl_.qualifying_simulation_}
    , decltype(_impl_.practice_starts_){from._impl_.practice_starts_}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:Practice)
}

inline void Practice::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.out_laps_){arena}
    , decltype(_impl_.installation_laps_){arena}
    , decltype(_impl_.aero_mapping_){arena}
    , decltype(_impl_.performance_runs_){arena}
    , decltype(_impl_.long_runs_){arena}
    , decltype(_impl_.race_simulation_){arena}
    , decltype(_impl_.qualifying_simulation_){arena}
    , decltype(_impl_.practice_starts_){arena}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

Practice::~Practice() {
  // @@protoc_insertion_point(destructor:Practice)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Practice::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.out_laps_.~RepeatedPtrField();
  _impl_.installation_laps_.~RepeatedPtrField();
  _impl_.aero_mapping_.~RepeatedPtrField();
  _impl_.performance_runs_.~RepeatedPtrField();
  _impl_.long_runs_.~RepeatedPtrField();
  _impl_.race_simulation_.~RepeatedPtrField();
  _impl_.qualifying_simulation_.~RepeatedPtrField();
  _impl_.practice_starts_.~RepeatedPtrField();
}

void Practice::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void Practice::Clear() {
// @@protoc_insertion_point(message_clear_start:Practice)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.out_laps_.Clear();
  _impl_.installation_laps_.Clear();
  _impl_.aero_mapping_.Clear();
  _impl_.performance_runs_.Clear();
  _impl_.long_runs_.Clear();
  _impl_.race_simulation_.Clear();
  _impl_.qualifying_simulation_.Clear();
  _impl_.practice_starts_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Practice::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated .Stint out_laps = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_out_laps(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else
          goto handle_unusual;
        continue;
      // repeated .Stint installation_laps = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_installation_laps(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<18>(ptr));
        } else
          goto handle_unusual;
        continue;
      // repeated .Stint aero_mapping = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_aero_mapping(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<26>(ptr));
        } else
          goto handle_unusual;
        continue;
      // repeated .Stint performance_runs = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_performance_runs(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<34>(ptr));
        } else
          goto handle_unusual;
        continue;
      // repeated .Stint long_runs = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 42)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_long_runs(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<42>(ptr));
        } else
          goto handle_unusual;
        continue;
      // repeated .Stint race_simulation = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 50)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_race_simulation(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<50>(ptr));
        } else
          goto handle_unusual;
        continue;
      // repeated .Stint qualifying_simulation = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 58)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_qualifying_simulation(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<58>(ptr));
        } else
          goto handle_unusual;
        continue;
      // repeated .Stint practice_starts = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 66)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_practice_starts(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<66>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Practice::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Practice)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .Stint out_laps = 1;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_out_laps_size()); i < n; i++) {
    const auto& repfield = this->_internal_out_laps(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(1, repfield, repfield.GetCachedSize(), target, stream);
  }

  // repeated .Stint installation_laps = 2;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_installation_laps_size()); i < n; i++) {
    const auto& repfield = this->_internal_installation_laps(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(2, repfield, repfield.GetCachedSize(), target, stream);
  }

  // repeated .Stint aero_mapping = 3;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_aero_mapping_size()); i < n; i++) {
    const auto& repfield = this->_internal_aero_mapping(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(3, repfield, repfield.GetCachedSize(), target, stream);
  }

  // repeated .Stint performance_runs = 4;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_performance_runs_size()); i < n; i++) {
    const auto& repfield = this->_internal_performance_runs(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(4, repfield, repfield.GetCachedSize(), target, stream);
  }

  // repeated .Stint long_runs = 5;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_long_runs_size()); i < n; i++) {
    const auto& repfield = this->_internal_long_runs(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(5, repfield, repfield.GetCachedSize(), target, stream);
  }

  // repeated .Stint race_simulation = 6;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_race_simulation_size()); i < n; i++) {
    const auto& repfield = this->_internal_race_simulation(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(6, repfield, repfield.GetCachedSize(), target, stream);
  }

  // repeated .Stint qualifying_simulation = 7;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_qualifying_simulation_size()); i < n; i++) {
    const auto& repfield = this->_internal_qualifying_simulation(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(7, repfield, repfield.GetCachedSize(), target, stream);
  }

  // repeated .Stint practice_starts = 8;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_practice_starts_size()); i < n; i++) {
    const auto& repfield = this->_internal_practice_starts(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(8, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Practice)
  return target;
}

size_t Practice::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Practice)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .Stint out_laps = 1;
  total_size += 1UL * this->_internal_out_laps_size();
  for (const auto& msg : this->_impl_.out_laps_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // repeated .Stint installation_laps = 2;
  total_size += 1UL * this->_internal_installation_laps_size();
  for (const auto& msg : this->_impl_.installation_laps_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // repeated .Stint aero_mapping = 3;
  total_size += 1UL * this->_internal_aero_mapping_size();
  for (const auto& msg : this->_impl_.aero_mapping_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // repeated .Stint performance_runs = 4;
  total_size += 1UL * this->_internal_performance_runs_size();
  for (const auto& msg : this->_impl_.performance_runs_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // repeated .Stint long_runs = 5;
  total_size += 1UL * this->_internal_long_runs_size();
  for (const auto& msg : this->_impl_.long_runs_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // repeated .Stint race_simulation = 6;
  total_size += 1UL * this->_internal_race_simulation_size();
  for (const auto& msg : this->_impl_.race_simulation_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // repeated .Stint qualifying_simulation = 7;
  total_size += 1UL * this->_internal_qualifying_simulation_size();
  for (const auto& msg : this->_impl_.qualifying_simulation_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // repeated .Stint practice_starts = 8;
  total_size += 1UL * this->_internal_practice_starts_size();
  for (const auto& msg : this->_impl_.practice_starts_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Practice::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    Practice::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Practice::GetClassData() const { return &_class_data_; }


void Practice::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<Practice*>(&to_msg);
  auto& from = static_cast<const Practice&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Practice)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.out_laps_.MergeFrom(from._impl_.out_laps_);
  _this->_impl_.installation_laps_.MergeFrom(from._impl_.installation_laps_);
  _this->_impl_.aero_mapping_.MergeFrom(from._impl_.aero_mapping_);
  _this->_impl_.performance_runs_.MergeFrom(from._impl_.performance_runs_);
  _this->_impl_.long_runs_.MergeFrom(from._impl_.long_runs_);
  _this->_impl_.race_simulation_.MergeFrom(from._impl_.race_simulation_);
  _this->_impl_.qualifying_simulation_.MergeFrom(from._impl_.qualifying_simulation_);
  _this->_impl_.practice_starts_.MergeFrom(from._impl_.practice_starts_);
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Practice::CopyFrom(const Practice& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Practice)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Practice::IsInitialized() const {
  return true;
}

void Practice::InternalSwap(Practice* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.out_laps_.InternalSwap(&other->_impl_.out_laps_);
  _impl_.installation_laps_.InternalSwap(&other->_impl_.installation_laps_);
  _impl_.aero_mapping_.InternalSwap(&other->_impl_.aero_mapping_);
  _impl_.performance_runs_.InternalSwap(&other->_impl_.performance_runs_);
  _impl_.long_runs_.InternalSwap(&other->_impl_.long_runs_);
  _impl_.race_simulation_.InternalSwap(&other->_impl_.race_simulation_);
  _impl_.qualifying_simulation_.InternalSwap(&other->_impl_.qualifying_simulation_);
  _impl_.practice_starts_.InternalSwap(&other->_impl_.practice_starts_);
}

::PROTOBUF_NAMESPACE_ID::Metadata Practice::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Practice_2eproto_getter, &descriptor_table_Practice_2eproto_once,
      file_level_metadata_Practice_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::Practice*
Arena::CreateMaybeMessage< ::Practice >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Practice >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
