// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: QualifyingSession.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_QualifyingSession_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_QualifyingSession_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "Lap.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_QualifyingSession_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_QualifyingSession_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_QualifyingSession_2eproto;
class QualifyingSession;
struct QualifyingSessionDefaultTypeInternal;
extern QualifyingSessionDefaultTypeInternal _QualifyingSession_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::QualifyingSession* Arena::CreateMaybeMessage<::QualifyingSession>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class QualifyingSession final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:QualifyingSession) */ {
 public:
  inline QualifyingSession() : QualifyingSession(nullptr) {}
  ~QualifyingSession() override;
  explicit PROTOBUF_CONSTEXPR QualifyingSession(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  QualifyingSession(const QualifyingSession& from);
  QualifyingSession(QualifyingSession&& from) noexcept
    : QualifyingSession() {
    *this = ::std::move(from);
  }

  inline QualifyingSession& operator=(const QualifyingSession& from) {
    CopyFrom(from);
    return *this;
  }
  inline QualifyingSession& operator=(QualifyingSession&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const QualifyingSession& default_instance() {
    return *internal_default_instance();
  }
  static inline const QualifyingSession* internal_default_instance() {
    return reinterpret_cast<const QualifyingSession*>(
               &_QualifyingSession_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(QualifyingSession& a, QualifyingSession& b) {
    a.Swap(&b);
  }
  inline void Swap(QualifyingSession* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(QualifyingSession* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  QualifyingSession* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<QualifyingSession>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const QualifyingSession& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const QualifyingSession& from) {
    QualifyingSession::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(QualifyingSession* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "QualifyingSession";
  }
  protected:
  explicit QualifyingSession(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kLapFieldNumber = 1,
  };
  // repeated .Lap lap = 1;
  int lap_size() const;
  private:
  int _internal_lap_size() const;
  public:
  void clear_lap();
  ::Lap* mutable_lap(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Lap >*
      mutable_lap();
  private:
  const ::Lap& _internal_lap(int index) const;
  ::Lap* _internal_add_lap();
  public:
  const ::Lap& lap(int index) const;
  ::Lap* add_lap();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Lap >&
      lap() const;

  // @@protoc_insertion_point(class_scope:QualifyingSession)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Lap > lap_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_QualifyingSession_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// QualifyingSession

// repeated .Lap lap = 1;
inline int QualifyingSession::_internal_lap_size() const {
  return _impl_.lap_.size();
}
inline int QualifyingSession::lap_size() const {
  return _internal_lap_size();
}
inline ::Lap* QualifyingSession::mutable_lap(int index) {
  // @@protoc_insertion_point(field_mutable:QualifyingSession.lap)
  return _impl_.lap_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Lap >*
QualifyingSession::mutable_lap() {
  // @@protoc_insertion_point(field_mutable_list:QualifyingSession.lap)
  return &_impl_.lap_;
}
inline const ::Lap& QualifyingSession::_internal_lap(int index) const {
  return _impl_.lap_.Get(index);
}
inline const ::Lap& QualifyingSession::lap(int index) const {
  // @@protoc_insertion_point(field_get:QualifyingSession.lap)
  return _internal_lap(index);
}
inline ::Lap* QualifyingSession::_internal_add_lap() {
  return _impl_.lap_.Add();
}
inline ::Lap* QualifyingSession::add_lap() {
  ::Lap* _add = _internal_add_lap();
  // @@protoc_insertion_point(field_add:QualifyingSession.lap)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Lap >&
QualifyingSession::lap() const {
  // @@protoc_insertion_point(field_list:QualifyingSession.lap)
  return _impl_.lap_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_QualifyingSession_2eproto
