// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Qualifying.proto

#include "Qualifying.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

PROTOBUF_CONSTEXPR Qualifying::Qualifying(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.session_1_)*/nullptr
  , /*decltype(_impl_.session_2_)*/nullptr
  , /*decltype(_impl_.session_3_)*/nullptr
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct QualifyingDefaultTypeInternal {
  PROTOBUF_CONSTEXPR QualifyingDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~QualifyingDefaultTypeInternal() {}
  union {
    Qualifying _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 QualifyingDefaultTypeInternal _Qualifying_default_instance_;
static ::_pb::Metadata file_level_metadata_Qualifying_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_Qualifying_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_Qualifying_2eproto = nullptr;

const uint32_t TableStruct_Qualifying_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Qualifying, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::Qualifying, _impl_.session_1_),
  PROTOBUF_FIELD_OFFSET(::Qualifying, _impl_.session_2_),
  PROTOBUF_FIELD_OFFSET(::Qualifying, _impl_.session_3_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::Qualifying)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::_Qualifying_default_instance_._instance,
};

const char descriptor_table_protodef_Qualifying_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\020Qualifying.proto\032\027QualifyingSession.pr"
  "oto\"\201\001\n\nQualifying\022%\n\tsession_1\030\001 \001(\0132\022."
  "QualifyingSession\022%\n\tsession_2\030\002 \001(\0132\022.Q"
  "ualifyingSession\022%\n\tsession_3\030\003 \001(\0132\022.Qu"
  "alifyingSessionb\006proto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_Qualifying_2eproto_deps[1] = {
  &::descriptor_table_QualifyingSession_2eproto,
};
static ::_pbi::once_flag descriptor_table_Qualifying_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_Qualifying_2eproto = {
    false, false, 183, descriptor_table_protodef_Qualifying_2eproto,
    "Qualifying.proto",
    &descriptor_table_Qualifying_2eproto_once, descriptor_table_Qualifying_2eproto_deps, 1, 1,
    schemas, file_default_instances, TableStruct_Qualifying_2eproto::offsets,
    file_level_metadata_Qualifying_2eproto, file_level_enum_descriptors_Qualifying_2eproto,
    file_level_service_descriptors_Qualifying_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_Qualifying_2eproto_getter() {
  return &descriptor_table_Qualifying_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_Qualifying_2eproto(&descriptor_table_Qualifying_2eproto);

// ===================================================================

class Qualifying::_Internal {
 public:
  static const ::QualifyingSession& session_1(const Qualifying* msg);
  static const ::QualifyingSession& session_2(const Qualifying* msg);
  static const ::QualifyingSession& session_3(const Qualifying* msg);
};

const ::QualifyingSession&
Qualifying::_Internal::session_1(const Qualifying* msg) {
  return *msg->_impl_.session_1_;
}
const ::QualifyingSession&
Qualifying::_Internal::session_2(const Qualifying* msg) {
  return *msg->_impl_.session_2_;
}
const ::QualifyingSession&
Qualifying::_Internal::session_3(const Qualifying* msg) {
  return *msg->_impl_.session_3_;
}
void Qualifying::clear_session_1() {
  if (GetArenaForAllocation() == nullptr && _impl_.session_1_ != nullptr) {
    delete _impl_.session_1_;
  }
  _impl_.session_1_ = nullptr;
}
void Qualifying::clear_session_2() {
  if (GetArenaForAllocation() == nullptr && _impl_.session_2_ != nullptr) {
    delete _impl_.session_2_;
  }
  _impl_.session_2_ = nullptr;
}
void Qualifying::clear_session_3() {
  if (GetArenaForAllocation() == nullptr && _impl_.session_3_ != nullptr) {
    delete _impl_.session_3_;
  }
  _impl_.session_3_ = nullptr;
}
Qualifying::Qualifying(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:Qualifying)
}
Qualifying::Qualifying(const Qualifying& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  Qualifying* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.session_1_){nullptr}
    , decltype(_impl_.session_2_){nullptr}
    , decltype(_impl_.session_3_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_session_1()) {
    _this->_impl_.session_1_ = new ::QualifyingSession(*from._impl_.session_1_);
  }
  if (from._internal_has_session_2()) {
    _this->_impl_.session_2_ = new ::QualifyingSession(*from._impl_.session_2_);
  }
  if (from._internal_has_session_3()) {
    _this->_impl_.session_3_ = new ::QualifyingSession(*from._impl_.session_3_);
  }
  // @@protoc_insertion_point(copy_constructor:Qualifying)
}

inline void Qualifying::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.session_1_){nullptr}
    , decltype(_impl_.session_2_){nullptr}
    , decltype(_impl_.session_3_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

Qualifying::~Qualifying() {
  // @@protoc_insertion_point(destructor:Qualifying)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Qualifying::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.session_1_;
  if (this != internal_default_instance()) delete _impl_.session_2_;
  if (this != internal_default_instance()) delete _impl_.session_3_;
}

void Qualifying::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void Qualifying::Clear() {
// @@protoc_insertion_point(message_clear_start:Qualifying)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaForAllocation() == nullptr && _impl_.session_1_ != nullptr) {
    delete _impl_.session_1_;
  }
  _impl_.session_1_ = nullptr;
  if (GetArenaForAllocation() == nullptr && _impl_.session_2_ != nullptr) {
    delete _impl_.session_2_;
  }
  _impl_.session_2_ = nullptr;
  if (GetArenaForAllocation() == nullptr && _impl_.session_3_ != nullptr) {
    delete _impl_.session_3_;
  }
  _impl_.session_3_ = nullptr;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Qualifying::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .QualifyingSession session_1 = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_session_1(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .QualifyingSession session_2 = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_session_2(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .QualifyingSession session_3 = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          ptr = ctx->ParseMessage(_internal_mutable_session_3(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Qualifying::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Qualifying)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .QualifyingSession session_1 = 1;
  if (this->_internal_has_session_1()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::session_1(this),
        _Internal::session_1(this).GetCachedSize(), target, stream);
  }

  // .QualifyingSession session_2 = 2;
  if (this->_internal_has_session_2()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(2, _Internal::session_2(this),
        _Internal::session_2(this).GetCachedSize(), target, stream);
  }

  // .QualifyingSession session_3 = 3;
  if (this->_internal_has_session_3()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(3, _Internal::session_3(this),
        _Internal::session_3(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Qualifying)
  return target;
}

size_t Qualifying::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Qualifying)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .QualifyingSession session_1 = 1;
  if (this->_internal_has_session_1()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.session_1_);
  }

  // .QualifyingSession session_2 = 2;
  if (this->_internal_has_session_2()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.session_2_);
  }

  // .QualifyingSession session_3 = 3;
  if (this->_internal_has_session_3()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.session_3_);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Qualifying::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    Qualifying::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Qualifying::GetClassData() const { return &_class_data_; }


void Qualifying::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<Qualifying*>(&to_msg);
  auto& from = static_cast<const Qualifying&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Qualifying)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_session_1()) {
    _this->_internal_mutable_session_1()->::QualifyingSession::MergeFrom(
        from._internal_session_1());
  }
  if (from._internal_has_session_2()) {
    _this->_internal_mutable_session_2()->::QualifyingSession::MergeFrom(
        from._internal_session_2());
  }
  if (from._internal_has_session_3()) {
    _this->_internal_mutable_session_3()->::QualifyingSession::MergeFrom(
        from._internal_session_3());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Qualifying::CopyFrom(const Qualifying& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Qualifying)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Qualifying::IsInitialized() const {
  return true;
}

void Qualifying::InternalSwap(Qualifying* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Qualifying, _impl_.session_3_)
      + sizeof(Qualifying::_impl_.session_3_)
      - PROTOBUF_FIELD_OFFSET(Qualifying, _impl_.session_1_)>(
          reinterpret_cast<char*>(&_impl_.session_1_),
          reinterpret_cast<char*>(&other->_impl_.session_1_));
}

::PROTOBUF_NAMESPACE_ID::Metadata Qualifying::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Qualifying_2eproto_getter, &descriptor_table_Qualifying_2eproto_once,
      file_level_metadata_Qualifying_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::Qualifying*
Arena::CreateMaybeMessage< ::Qualifying >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Qualifying >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
