// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Race.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_Race_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_Race_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "Stint.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_Race_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_Race_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_Race_2eproto;
class Race;
struct RaceDefaultTypeInternal;
extern RaceDefaultTypeInternal _Race_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::Race* Arena::CreateMaybeMessage<::Race>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class Race final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Race) */ {
 public:
  inline Race() : Race(nullptr) {}
  ~Race() override;
  explicit PROTOBUF_CONSTEXPR Race(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Race(const Race& from);
  Race(Race&& from) noexcept
    : Race() {
    *this = ::std::move(from);
  }

  inline Race& operator=(const Race& from) {
    CopyFrom(from);
    return *this;
  }
  inline Race& operator=(Race&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Race& default_instance() {
    return *internal_default_instance();
  }
  static inline const Race* internal_default_instance() {
    return reinterpret_cast<const Race*>(
               &_Race_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Race& a, Race& b) {
    a.Swap(&b);
  }
  inline void Swap(Race* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Race* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Race* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Race>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Race& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Race& from) {
    Race::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Race* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Race";
  }
  protected:
  explicit Race(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kStintFieldNumber = 1,
  };
  // repeated .Stint stint = 1;
  int stint_size() const;
  private:
  int _internal_stint_size() const;
  public:
  void clear_stint();
  ::Stint* mutable_stint(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Stint >*
      mutable_stint();
  private:
  const ::Stint& _internal_stint(int index) const;
  ::Stint* _internal_add_stint();
  public:
  const ::Stint& stint(int index) const;
  ::Stint* add_stint();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Stint >&
      stint() const;

  // @@protoc_insertion_point(class_scope:Race)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Stint > stint_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Race_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Race

// repeated .Stint stint = 1;
inline int Race::_internal_stint_size() const {
  return _impl_.stint_.size();
}
inline int Race::stint_size() const {
  return _internal_stint_size();
}
inline ::Stint* Race::mutable_stint(int index) {
  // @@protoc_insertion_point(field_mutable:Race.stint)
  return _impl_.stint_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Stint >*
Race::mutable_stint() {
  // @@protoc_insertion_point(field_mutable_list:Race.stint)
  return &_impl_.stint_;
}
inline const ::Stint& Race::_internal_stint(int index) const {
  return _impl_.stint_.Get(index);
}
inline const ::Stint& Race::stint(int index) const {
  // @@protoc_insertion_point(field_get:Race.stint)
  return _internal_stint(index);
}
inline ::Stint* Race::_internal_add_stint() {
  return _impl_.stint_.Add();
}
inline ::Stint* Race::add_stint() {
  ::Stint* _add = _internal_add_stint();
  // @@protoc_insertion_point(field_add:Race.stint)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Stint >&
Race::stint() const {
  // @@protoc_insertion_point(field_list:Race.stint)
  return _impl_.stint_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_Race_2eproto
