// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Stint.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_Stint_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_Stint_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "Lap.pb.h"
#include "Setup.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_Stint_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_Stint_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_Stint_2eproto;
class Stint;
struct StintDefaultTypeInternal;
extern StintDefaultTypeInternal _Stint_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::Stint* Arena::CreateMaybeMessage<::Stint>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class Stint final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Stint) */ {
 public:
  inline Stint() : Stint(nullptr) {}
  ~Stint() override;
  explicit PROTOBUF_CONSTEXPR Stint(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Stint(const Stint& from);
  Stint(Stint&& from) noexcept
    : Stint() {
    *this = ::std::move(from);
  }

  inline Stint& operator=(const Stint& from) {
    CopyFrom(from);
    return *this;
  }
  inline Stint& operator=(Stint&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Stint& default_instance() {
    return *internal_default_instance();
  }
  static inline const Stint* internal_default_instance() {
    return reinterpret_cast<const Stint*>(
               &_Stint_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Stint& a, Stint& b) {
    a.Swap(&b);
  }
  inline void Swap(Stint* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Stint* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Stint* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Stint>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Stint& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Stint& from) {
    Stint::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Stint* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Stint";
  }
  protected:
  explicit Stint(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kLapFieldNumber = 1,
    kSetupFieldNumber = 2,
  };
  // repeated .Lap lap = 1;
  int lap_size() const;
  private:
  int _internal_lap_size() const;
  public:
  void clear_lap();
  ::Lap* mutable_lap(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Lap >*
      mutable_lap();
  private:
  const ::Lap& _internal_lap(int index) const;
  ::Lap* _internal_add_lap();
  public:
  const ::Lap& lap(int index) const;
  ::Lap* add_lap();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Lap >&
      lap() const;

  // .Setup setup = 2;
  bool has_setup() const;
  private:
  bool _internal_has_setup() const;
  public:
  void clear_setup();
  const ::Setup& setup() const;
  PROTOBUF_NODISCARD ::Setup* release_setup();
  ::Setup* mutable_setup();
  void set_allocated_setup(::Setup* setup);
  private:
  const ::Setup& _internal_setup() const;
  ::Setup* _internal_mutable_setup();
  public:
  void unsafe_arena_set_allocated_setup(
      ::Setup* setup);
  ::Setup* unsafe_arena_release_setup();

  // @@protoc_insertion_point(class_scope:Stint)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Lap > lap_;
    ::Setup* setup_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Stint_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Stint

// repeated .Lap lap = 1;
inline int Stint::_internal_lap_size() const {
  return _impl_.lap_.size();
}
inline int Stint::lap_size() const {
  return _internal_lap_size();
}
inline ::Lap* Stint::mutable_lap(int index) {
  // @@protoc_insertion_point(field_mutable:Stint.lap)
  return _impl_.lap_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Lap >*
Stint::mutable_lap() {
  // @@protoc_insertion_point(field_mutable_list:Stint.lap)
  return &_impl_.lap_;
}
inline const ::Lap& Stint::_internal_lap(int index) const {
  return _impl_.lap_.Get(index);
}
inline const ::Lap& Stint::lap(int index) const {
  // @@protoc_insertion_point(field_get:Stint.lap)
  return _internal_lap(index);
}
inline ::Lap* Stint::_internal_add_lap() {
  return _impl_.lap_.Add();
}
inline ::Lap* Stint::add_lap() {
  ::Lap* _add = _internal_add_lap();
  // @@protoc_insertion_point(field_add:Stint.lap)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Lap >&
Stint::lap() const {
  // @@protoc_insertion_point(field_list:Stint.lap)
  return _impl_.lap_;
}

// .Setup setup = 2;
inline bool Stint::_internal_has_setup() const {
  return this != internal_default_instance() && _impl_.setup_ != nullptr;
}
inline bool Stint::has_setup() const {
  return _internal_has_setup();
}
inline const ::Setup& Stint::_internal_setup() const {
  const ::Setup* p = _impl_.setup_;
  return p != nullptr ? *p : reinterpret_cast<const ::Setup&>(
      ::_Setup_default_instance_);
}
inline const ::Setup& Stint::setup() const {
  // @@protoc_insertion_point(field_get:Stint.setup)
  return _internal_setup();
}
inline void Stint::unsafe_arena_set_allocated_setup(
    ::Setup* setup) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.setup_);
  }
  _impl_.setup_ = setup;
  if (setup) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Stint.setup)
}
inline ::Setup* Stint::release_setup() {
  
  ::Setup* temp = _impl_.setup_;
  _impl_.setup_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::Setup* Stint::unsafe_arena_release_setup() {
  // @@protoc_insertion_point(field_release:Stint.setup)
  
  ::Setup* temp = _impl_.setup_;
  _impl_.setup_ = nullptr;
  return temp;
}
inline ::Setup* Stint::_internal_mutable_setup() {
  
  if (_impl_.setup_ == nullptr) {
    auto* p = CreateMaybeMessage<::Setup>(GetArenaForAllocation());
    _impl_.setup_ = p;
  }
  return _impl_.setup_;
}
inline ::Setup* Stint::mutable_setup() {
  ::Setup* _msg = _internal_mutable_setup();
  // @@protoc_insertion_point(field_mutable:Stint.setup)
  return _msg;
}
inline void Stint::set_allocated_setup(::Setup* setup) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.setup_);
  }
  if (setup) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(setup));
    if (message_arena != submessage_arena) {
      setup = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, setup, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.setup_ = setup;
  // @@protoc_insertion_point(field_set_allocated:Stint.setup)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_Stint_2eproto
